export const opsReferralsCopy = {
	pageTitle: 'Referrals',
	pageDescription:
		'Manage referrers and review bookings attributed to them for compensation tracking.',
	referrersSectionTitle: 'Referrers',
	referredBookingsTitle: 'Referred bookings',
	newReferrer: 'Add referrer',
	editReferrer: 'Edit referrer',
	saveReferrer: 'Save referrer',
	fieldName: 'Name',
	fieldCode: 'Code (optional)',
	fieldEmail: 'Email (optional)',
	fieldStatus: 'Status',
	fieldCommission: 'Commission % (optional)',
	statusActive: 'Active',
	statusInactive: 'Inactive',
	tableReferrer: 'Referrer',
	tableBookings: 'Bookings',
	tableReference: 'Reference',
	tableCustomer: 'Customer',
	tablePickup: 'Pickup',
	tableStatus: 'Status',
	tableAmount: 'Amount',
	emptyReferrers: 'No referrers yet. Add one to attribute ops bookings.',
	emptyReferred: 'No referred bookings yet.',
	loadError: 'Could not load referrals data.',
} as const
