/**
 * Copy for **`/ops/calendar`** (Story 17.14, **NFR.17.8**). Shuttle ops vocabulary (**NFR.17.7**).
 */
export const opsCalendarCopy = {
	pageTitle: 'Calendar',
	pageDescription:
		'Week, month, or list of scheduled trips. Select an event for assignment summary.',
	emptyWeekTitle: 'No trips this week',
	emptyWeekDescription: 'Trips that fall in the selected week appear here.',
	emptyMonthTitle: 'No trips in this period',
	emptyMonthDescription: 'Trips that fall in the displayed month grid appear here.',
	viewToggleGroupAria: 'Calendar layout',
	viewWeek: 'Week grid',
	viewMonth: 'Month grid',
	viewList: 'Agenda list',
	prevWeekAria: 'Previous week',
	nextWeekAria: 'Next week',
	thisWeek: 'This week',
	prevMonthAria: 'Previous month',
	nextMonthAria: 'Next month',
	thisMonth: 'This month',
	gridRegionAria: 'Week calendar, trips as timed events',
	gridMonthAria: 'Month calendar, trips as chips',
	listRegionAria: 'Agenda list for this week',
	eventOpenDetailAria: (title: string) => `Open details: ${title}`,
	detailRailTitle: 'Trip details',
	sectionSchedule: 'Schedule',
	sectionVehicle: 'Vehicle',
	sectionClient: 'Client / booking',
	sectionDriver: 'Driver',
	sectionNotes: 'Notes',
	noNotes: 'No notes on this trip.',
	serviceTypeLabel: 'Service type',
	openTripsPage: 'Open in Trips',
} as const
