export const opsTeamCopy = {
	pageTitle: 'Team',
	pageDescription:
		'Platform admins and dispatchers who can access the ops console. Invite new members by email; they receive login instructions to set a password.',
	inviteButton: 'Invite member',
	inviteDialogTitle: 'Invite team member',
	inviteDialogDescription:
		'An email is sent with a link to set their password and sign in to the ops console.',
	listCaption: 'Operations team members',
	listEmpty: 'No team members yet. Invite your first dispatcher or admin.',
	listLoadError: 'Team members could not be loaded.',
	tableName: 'Name',
	tableEmail: 'Email',
	tableRole: 'Role',
	tableStatus: 'Status',
	tablePhone: 'Phone',
	statusActive: 'Active',
	statusInactive: 'Inactive',
	memberDetailBack: 'Back to team',
	memberDetailTitle: 'Team member',
	memberNotFound: 'Team member not found.',
	memberLoadError: 'Could not load this team member.',
	activateMember: 'Activate',
	deactivateMember: 'Deactivate',
	deleteMember: 'Remove member',
	deleteDialogTitle: 'Remove this team member?',
	deleteDialogDescription:
		'This permanently deletes their account and profile. They will no longer be able to sign in. This cannot be undone.',
	deleteConfirm: 'Remove member',
	deleteCancel: 'Cancel',
	deleteSelfError: 'You cannot remove your own account.',
	deleteLastAdminError: 'Cannot remove the last platform admin.',
	statusUpdateSuccess: 'Member status updated.',
	deleteSuccess: 'Member removed.',
	inviteSuccess: 'Invitation sent. They will receive an email to set up their account.',
	fieldFullName: 'Full name',
	fieldEmail: 'Email',
	fieldPhone: 'Phone (optional)',
	fieldRole: 'Role',
	roleDispatcher: 'Dispatcher',
	roleAdmin: 'Admin',
	sendInvite: 'Send invite',
	sendingInvite: 'Sending…',
	cancel: 'Cancel',
} as const
