export const opsProfileCopy = {
	pageTitle: 'Your profile',
	pageIntro: 'Update your name and phone number, or change your password for the ops console.',
	backToDashboard: 'Back to dashboard',
	sectionPersonalTitle: 'Personal details',
	sectionPersonalDescription: 'Your work email is managed by your account administrator.',
	sectionSecurityTitle: 'Password',
	sectionSecurityDescription: 'Choose a strong password you do not use elsewhere.',
	fieldFirstName: 'First name',
	fieldLastName: 'Last name',
	fieldWorkEmail: 'Work email',
	fieldWorkEmailHint: 'Contact a platform admin to change your sign-in email.',
	fieldPhone: 'Phone',
	fieldPhoneHint: 'Optional. Stored in international format when valid.',
	fieldCurrentPassword: 'Current password',
	fieldNewPassword: 'New password',
	fieldConfirmPassword: 'Confirm new password',
	savePersonal: 'Save details',
	savePersonalPending: 'Saving…',
	savePassword: 'Update password',
	savePasswordPending: 'Updating…',
	personalSuccess: 'Profile updated.',
	passwordSuccess: 'Password updated.',
	personalErrorFirstNameRequired: 'First name is required.',
	personalErrorPhone: 'Enter a valid phone number or leave the field empty.',
	personalErrorForm: 'Check the form and try again.',
	personalErrorGeneric: 'Could not save your profile. Try again.',
	passwordErrorWeak: 'Password must be at least 8 characters.',
	passwordErrorMismatch: 'New passwords do not match.',
	passwordErrorWrongCurrent: 'Current password is incorrect.',
	passwordErrorGeneric: 'Could not update your password. Try again.',
	gateNoSession: 'You must be signed in to update your profile.',
	personalFormAria: 'Update name and phone',
	passwordFormAria: 'Change password',
} as const
