export const PRICING_CONFIG_REPOSITORY = Symbol('PRICING_CONFIG_REPOSITORY');
export const VEHICLE_PRICING_REPOSITORY = Symbol('VEHICLE_PRICING_REPOSITORY');
export const PRICING_SERVICE = Symbol('PRICING_SERVICE');
