/**
 * Shared SaaS presentation primitives (**FE.18.13**). Ops entry points remain **`Ops*`** re-exports under **`src/features/ops/components/`**.
 */
export type { SaasTheme } from './saas-theme'
export { saasCls } from './saas-class-names'
export * from './chart-utils'
export * from './chart-tones'
export { ChartEmpty } from './ChartEmpty'
export { Sparkline } from './Sparkline'
export type { SparklineProps } from './Sparkline'
export { BarChart } from './BarChart'
export type { BarChartProps, BarChartSeries } from './BarChart'
export { DonutChart } from './DonutChart'
export type { DonutChartProps, DonutSlice } from './DonutChart'
export { AreaChart } from './AreaChart'
export type { AreaChartPoint, AreaChartProps } from './AreaChart'
export { KpiCard } from './KpiCard'
export type { KpiCardProps } from './KpiCard'
export { KpiCardOverflowMenu } from './KpiCardOverflowMenu'
export type { KpiCardOverflowMenuProps } from './KpiCardOverflowMenu'
export { StatusPill } from './StatusPill'
export type { StatusPillProps } from './StatusPill'
export { AvatarCell } from './AvatarCell'
export type { AvatarCellProps } from './AvatarCell'
export { Pagination } from './Pagination'
export type { PaginationProps } from './Pagination'
export { SplitView } from './SplitView'
export type { SplitViewProps } from './SplitView'
export { DetailRail } from './DetailRail'
export type { DetailRailProps } from './DetailRail'
export { EmptyState } from './EmptyState'
export type { EmptyStateProps } from './EmptyState'
export { LoadingRegion } from './LoadingRegion'
export type { LoadingRegionProps } from './LoadingRegion'
export { ErrorState } from './ErrorState'
export type { ErrorStateProps, ErrorStateVariant } from './ErrorState'
