-- Align schema naming with Vestroo premium transport domain (not public-bus transit).
alter table public.bus_route_stops rename column bus_route_id to service_route_id;
alter table public.bus_route_stops rename column stop_id to service_point_id;
alter table public.bus_schedules rename column bus_route_id to service_route_id;
alter table public.bus_trips rename column bus_schedule_id to service_pattern_id;
alter table public.bus_trips rename column bus_route_id to service_route_id;
alter table public.driver_bus_schedules rename column bus_route_id to service_route_id;
alter table public.driver_bus_schedules rename column current_stop_id to current_point_id;
alter table public.driver_bus_schedules rename column completed_stop_ids to completed_point_ids;
alter table public.tickets rename column bus_route_id to service_route_id;
alter table public.tickets rename column bus_trip_id to service_run_id;
alter table public.tickets rename column from_stop_id to from_point_id;
alter table public.tickets rename column to_stop_id to to_point_id;
alter table public.trip_seats rename column bus_trip_id to service_run_id;
alter table public.trip_seats rename column from_stop_id to from_point_id;
alter table public.trip_seats rename column to_stop_id to to_point_id;
alter table public.bus_trackings rename column driver_bus_schedule_id to chauffeur_assignment_id;
alter table public.bus_trackings rename column bus_trip_id to service_run_id;
alter table public.bus_trackings rename column current_stop_id to current_point_id;
alter table public.bus_trackings rename column next_stop_id to next_point_id;
alter index if exists idx_tickets_bus_trip rename to idx_tickets_service_run;
alter table public.bus_stops rename to service_points;
alter table public.bus_routes rename to service_routes;
alter table public.bus_route_stops rename to service_route_points;
alter table public.bus_schedules rename to service_patterns;
alter table public.bus_trips rename to service_runs;
alter table public.driver_bus_schedules rename to chauffeur_assignments;
alter table public.bus_trackings rename to vehicle_trackings;
alter trigger bus_stops_set_updated_at on public.service_points rename to service_points_set_updated_at;
alter trigger bus_routes_set_updated_at on public.service_routes rename to service_routes_set_updated_at;
alter trigger bus_schedules_set_updated_at on public.service_patterns rename to service_patterns_set_updated_at;
alter trigger bus_trips_set_updated_at on public.service_runs rename to service_runs_set_updated_at;
alter trigger driver_bus_schedules_set_updated_at on public.chauffeur_assignments rename to chauffeur_assignments_set_updated_at;
alter trigger bus_trackings_set_updated_at on public.vehicle_trackings rename to vehicle_trackings_set_updated_at;
